# ndarray

In [7]:
import numpy as np

# 1d array

arr1 = np.array([1, 2, 3 , 4, 5])
print(type(arr1))

# 2d array

arr2 = np.array([[1, 2, 3],
                [4, 5, 6]])

#3d array
arr3 = np.array([[[1, 2, 3],
                 [4, 5, 6]],
                 [[7, 8, 9],
                 [10, 11, 12]]])

<class 'numpy.ndarray'>


# Array attributes

In [9]:
# dimension
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)


#shape
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)


#data type
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)


#size
print(arr1.size)
print(arr2.size)
print(arr3.size)



1
2
3
(5,)
(2, 3)
(2, 2, 3)
int64
int64
int64
5
6
12


# ndarray data type

In [14]:
arr = np.array([1, 2, 3])
print(arr.dtype)

arr = np.array ([1.5, 2.5, 3.5])
print(arr.dtype)

int64
float64


# ndarray creation from Existing data

In [2]:
import numpy as np
#list

lst = [10,20,30,40 , 40.5]

arr = np.array(lst, dtype=np.int32)

# print(arr)
# print(type(arr))
# print(arr.dtype)


mixed_lst = [10, True , 'Hello' ]

arr = np.array(mixed_lst)

# print(arr)
# print(type(arr))
# print(arr.dtype)


matrix = [ [1,2,3], # row1
           [4,5,6] #row2
                ]

arr = np.array(matrix)

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
2


In [3]:
#tuple

tpl = (10,20,30)

arr = np.array(tpl,dtype=np.int32)
print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

int32
[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1


In [4]:
#set

st = { 1, 2, 3 }

arr = np.array(list(st))
# print(arr.dtype)
arr = arr.astype(np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)


[1 2 3]
<class 'numpy.ndarray'>
int16
(3,)
1


In [6]:
# dictionary

dc = { 'a' : 10 , 'b' : 20 , 'c' :30 }

keys = dc.keys()
values = dc.values()
items = dc.items()

In [7]:
#keys to ndarray
arr = np.array(list(keys))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

['a' 'b' 'c']
<class 'numpy.ndarray'>
<U1
(3,)
1
3


In [8]:
#values to ndarray
arr = np.array(list(values))
print(arr)
arr = arr.astype(np.int16)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[10 20 30]
<class 'numpy.ndarray'>
int16
(3,)
1
3


In [9]:
#items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2
6


# Creating ndarray from scratch

In [11]:
zeros = np.zeros((2,3))
print("Zeros array: \n", zeros)

ones = np.ones((3,3))
print("Ones array: \n", ones)

sequence = np.arange (0, 10, 2)
print ("Sequence array: \n", sequence)

Zeros array: 
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones array: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Sequence array: 
 [0 2 4 6 8]


# array creation with random values

In [12]:
# np.random.rand(shape)

arr = np.random.rand(2,3) # 0 ->1

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.37483785 0.73484888 0.17727428]
 [0.35851472 0.99426347 0.11201076]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [13]:
# np.random.randint(start,end, shape)

arr = np.random.randint(1,10 , (2,3))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[2 7 4]
 [8 1 6]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [14]:
# np.random.uniform(start,end, shape)

arr = np.random.uniform(50,100, (3,3,4))

print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[[79.19626398 61.39846634 80.83817469 87.10242561]
  [71.60859633 71.33715551 68.80539268 56.20770035]
  [73.29423815 79.78857077 57.86897583 94.60932542]]

 [[82.42279623 94.82085584 61.54276096 60.23196462]
  [66.38655121 63.30263866 82.0641893  68.00104699]
  [85.81328139 70.74164783 78.83683139 89.14637982]]

 [[54.44357644 67.45244751 82.08616858 97.38438703]
  [52.34278194 54.4611372  74.28985531 51.63022761]
  [54.11831219 79.79575069 86.97258136 51.72221131]]]
<class 'numpy.ndarray'>
float64
(3, 3, 4)
3
36


# ndarray creation from range

In [2]:
import numpy as np
# np.arange(first , end , step ) -> similar to range function

arr = np.arange(1 , 10 ,1 )
mat = arr.reshape(3,3)

print(arr)
print(mat)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>
int64
(9,)
1
9


In [3]:
# np.linspace(start , end(included) , koita)

arr = np.linspace(0, 4 ,6)


print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[0.  0.8 1.6 2.4 3.2 4. ]
<class 'numpy.ndarray'>
float64
(6,)
1
6


In [5]:
# np.logspace(start , end(included) , koita )

arr = np.logspace(0 , 4 ,6, base=2)

print(arr)


[ 1.          1.74110113  3.03143313  5.27803164  9.18958684 16.        ]


# Indexing and Slicing

In [17]:
#indexing

print(arr1)
print(arr2)

# arr1[2] = 100

# print(arr1)
arr2[0][2]= 100

print(arr2)

[1 2 3 4 5]
[[  1   2 100]
 [  4   5   6]]
[[  1   2 100]
 [  4   5   6]]


In [18]:
#slicing
#1d = arr[start:end:step]

arr1_mod = arr1[1:4].copy()
arr1[1] = 2


arr1_mod[2] = 200
print(arr1_mod) 
print(arr1)


[  2   3 200]
[1 2 3 4 5]


In [19]:
#2d slicing
# arr[ row_start : row_end : step , column_start : column_end : step ]

# print(arr2)

#getting a row

row_0 = arr2[0:1 ,]

row_1= arr2[1: , ]

# print(row_0)
# print(row_1)


#getting a column

col_0 = arr2[:: ,0:1]
col_1 = arr2[::,1:2]

print(col_0)
print(col_1)

#getting a portion


portion = arr2[:: , 0:2]

print(portion)

[[1]
 [4]]
[[2]
 [5]]
[[1 2]
 [4 5]]
