# ndarray Manipulation

In [34]:
import numpy as np
arr = np.random.randint(1, 100, size=(10, 5))
arr

array([[27,  1, 97, 93, 33],
       [10, 87, 65, 55, 76],
       [98, 14, 63, 60, 76],
       [97, 79,  4, 88, 40],
       [98,  5,  9, 61, 40],
       [21, 42, 91, 38,  4],
       [77, 36, 15, 74, 43],
       [70, 85, 35, 80, 51],
       [61, 46, 91, 81, 13],
       [22, 14, 15, 65,  7]], dtype=int32)

In [35]:
arr2 = arr.reshape(5, 10)
arr2


array([[27,  1, 97, 93, 33, 10, 87, 65, 55, 76],
       [98, 14, 63, 60, 76, 97, 79,  4, 88, 40],
       [98,  5,  9, 61, 40, 21, 42, 91, 38,  4],
       [77, 36, 15, 74, 43, 70, 85, 35, 80, 51],
       [61, 46, 91, 81, 13, 22, 14, 15, 65,  7]], dtype=int32)

In [36]:
print(arr2.ndim)
flatten = arr2.flatten()
print(flatten)
print(flatten.ndim)

2
[27  1 97 93 33 10 87 65 55 76 98 14 63 60 76 97 79  4 88 40 98  5  9 61
 40 21 42 91 38  4 77 36 15 74 43 70 85 35 80 51 61 46 91 81 13 22 14 15
 65  7]
1


In [37]:
column_wise_flatten = np.ravel(arr2, order='F')
column_wise_flatten

array([27, 98, 98, 77, 61,  1, 14,  5, 36, 46, 97, 63,  9, 15, 91, 93, 60,
       61, 74, 81, 33, 76, 40, 43, 13, 10, 97, 21, 70, 22, 87, 79, 42, 85,
       14, 65,  4, 91, 35, 15, 55, 88, 38, 80, 65, 76, 40,  4, 51,  7],
      dtype=int32)

In [38]:
a = np.random.randint(1, 10, size=(2, 3))
b = np.random.randint(20, 30, size=(2, 3))

## concatenate

In [39]:
con_row = np.concatenate((a,b), axis=0) # row_wise
con_col = np.concatenate((a,b), axis=1) # column_wise

print(con_row)
print(con_col)

[[ 1  4  2]
 [ 2  2  2]
 [26 22 29]
 [20 26 28]]
[[ 1  4  2 26 22 29]
 [ 2  2  2 20 26 28]]


## transpose

In [40]:
mt = np.array([[10, 20, 30],
              [40, 50, 60]])
transpose = mt.T
print(transpose)

[[10 40]
 [20 50]
 [30 60]]


## splited array

In [41]:
a = np.random.randint(1, 10, size=(10, ))
print(a)
splited_array = np.array_split(a, 3)
print(splited_array)

#split --> equal devision
splited = np.split(a, 3)
print(splited)

[1 5 2 7 2 4 2 4 7 3]
[array([1, 5, 2, 7], dtype=int32), array([2, 4, 2], dtype=int32), array([4, 7, 3], dtype=int32)]


ValueError: array split does not result in an equal division

# Arithmetic Operators and Mathematical function

In [42]:
x = np.array([10, 20, 30, 40, 50])
y = np.array([1, 2, 3, 4, 5])

add = np.add(x, y)
print(add)

sub = x - y
print(sub)

mul = x * y
print(mul)

div = x / y
print(div)

rem = x % y
print(rem)

[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]
[0 0 0 0 0]


In [43]:
# mathmatical function

# trigonometry
# sin, cos, tan takes values in radian

sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

tan_val = np.tan(x)
print(tan_val)


deg_con = np.rad2deg(x)
print(deg_con)

[-0.54402111  0.91294525 -0.98803162  0.74511316 -0.26237485]
[-0.83907153  0.40808206  0.15425145 -0.66693806  0.96496603]
[ 0.64836083  2.23716094 -6.4053312  -1.11721493 -0.27190061]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052 2864.78897565]


In [44]:
x = np.array([10, 16, 20, 30, 40, 50])
# log

base_10_log_val = np.log10(x)
print(base_10_log_val)

# squer root

sqrt = np.sqrt(x)
print(sqrt)

[1.         1.20411998 1.30103    1.47712125 1.60205999 1.69897   ]
[3.16227766 4.         4.47213595 5.47722558 6.32455532 7.07106781]


# ligical function

In [45]:
x = np.array([10, 20, 30, 40, 50])
y = np.array([1, 2, 3, 4, 5])

# comparison  >, <, >=, >=, ==, !=

geater_then = x > y
print(geater_then)

equal = x == y
print(equal)

# all() --> is all true
# any() --> is one is true

print(np.all(geater_then))
print(np.any(equal))

[ True  True  True  True  True]
[False False False False False]
True
False


# Shorting

In [46]:
# 1d sorting

x = np.array([10, 6, 2, 20, 5, 15, 12, 18])

sort_1d = np.sort(x)
print(sort_1d)



[ 2  5  6 10 12 15 18 20]


In [47]:
# 2d sorting

mat = np.array([[10, 3, 5],
               [8, 4, 9]])

hor_sort = np.sort(mat, axis = 1)   # horizon axis = 1
print(hor_sort)

ver_sort = np.sort(mat, axis = 0)   # vertical axis = 0
print(ver_sort)


[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


# searching

In [48]:
# where

x = np.array([10, 6, 2, 20, 5, 15, 12, 18])

index_1 = np.where(x == 20)
print(index_1)

index_2 = np.where(x > 10)
print(index_2)

arr = np.where( x > 5, x, 0)
print(arr)

(array([3]),)
(array([3, 5, 6, 7]),)
[10  6  0 20  0 15 12 18]


In [49]:
index = np.where(mat > 8)
print(index)

arr = np.where( mat > 5, mat, 0)
print(arr)

(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 8  0  9]]


In [50]:
# maximum value index

max_val = np.argmax(x)
print(max_val)

# minimum value index

min_val = np.argmin(x)
print(min_val)

3
2


# counting

In [51]:
a = np.random.randint(1, 100, size=(100, ))
print(a)

[94 44 65 82 43 24 12 94 44 79 30 11 99 11 33 44 17  1 32 66 22 18 36  2
 91 82 81 57 16 94 39 64 91 69 31 22 94 39 35 87 78 21 84 85 61 92 91 19
 60 19 46 25 65 72 93 64 86 10 80 79 40 48  2 93 47 99 24  1  2 44 43 16
 31 93 28 20  7 35 86 70  2 83 57 83 56 91 81 10 58 35 83 56 57 14  1 35
 86 87 88 74]


In [52]:
value = np.count_nonzero(a > 60)
print(value)

43


In [53]:
uniq_val, count = np.unique(a, return_counts=True)
print(uniq_val)
print(count)

[ 1  2  7 10 11 12 14 16 17 18 19 20 21 22 24 25 28 30 31 32 33 35 36 39
 40 43 44 46 47 48 56 57 58 60 61 64 65 66 69 70 72 74 78 79 80 81 82 83
 84 85 86 87 88 91 92 93 94 99]
[3 4 1 2 2 1 1 2 1 1 2 1 1 2 2 1 1 1 2 1 1 4 1 2 1 2 4 1 1 1 2 3 1 1 1 2 2
 1 1 1 1 1 1 2 1 2 2 3 1 1 3 2 1 4 1 3 4 2]


# Statistical function

In [54]:
data = np.genfromtxt('student_grades.csv', delimiter=',', skip_header = 1)
print(data)

[[ 1. 78. 85. 82.]
 [ 2. 56. 67. 72.]
 [ 3. 89. 92. 88.]
 [ 4. 45. 52. 58.]
 [ 5. 70. 75. 80.]
 [ 6. 92. 90. 91.]
 [ 7. 61. 60. 62.]
 [ 8. 55. 57. 54.]
 [ 9. 88. 89. 87.]
 [10. 74. 70. 76.]
 [11. 66. 69. 68.]
 [12. 80. 82. 81.]
 [13. 59. 64. 60.]
 [14. 73. 78. 74.]
 [15. 91. 93. 90.]
 [16. 68. 71. 69.]
 [17. 77. 79. 78.]
 [18. 84. 86. 85.]
 [19. 62. 63. 65.]
 [20. 95. 97. 96.]]


In [55]:
math_mark = data[:, 1]
print(math_mark)

[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
 62. 95.]


In [56]:
# statistics

max_math_mark = np.max(math_mark)
print(max_math_mark)

min_math_mark = np.min(math_mark)
print(min_math_mark)

avarage_math_mark = np.mean(math_mark)
print(avarage_math_mark)

median_math_mark = np.median(math_mark)
print(median_math_mark)

std_math_mark = np.std(math_mark)
print(std_math_mark)

95.0
45.0
73.15
73.5
13.788672887555204


# Linear Algebra

In [57]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])

b = np.array([[7, 8],
             [9, 10],
             [11, 12]])

dot_product = np.dot(a, b)
print(dot_product)

trace = np.trace(b)
print(trace)

[[ 58  64]
 [139 154]]
17


In [58]:
sqr_matrix = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
det_of_sqr = np.linalg.det(sqr_matrix)
print(det_of_sqr)

rank_of_sqr = np.linalg.matrix_rank(sqr_matrix)
print(rank_of_sqr)

6.66133814775094e-16
2
